apiVersion: v1
kind: AIAnalysis
analysis_id: drift-explain-canary
requester_role: operator
tenant:
  id: canary
  scope: tenant
analysis_type: drift_explain
inputs:
  evidence_refs:
    - evidence/ai/analysis/canary/fixtures/drift-summary.md
  time_window:
    start_utc: "2026-01-01T00:00:00Z"
    end_utc: "2026-01-02T00:00:00Z"
output_format: markdown
max_tokens: 1200
